defaults:
- image_encoder: vit
- text_encoder: bert-large
- dataset: flickr

projection_dim: 256  # Dimension to project both image and text embeddings

training:
  epochs: 2
  batch_size: 64
  learning_rate: 1e-3
  temperature: 0.1
