defaults:
  - _self_
  - clip

hydra:
  run:
    dir: outputs/${hydra.job.name}/${now:%Y-%m-%d_%H-%M-%S}

# General training configurations
training:

# Reference to sub-configurations for specific components
dataset:
  ${dataset}

text_encoder:
  ${text_encoder}

image_encoder:
  ${image_encoder}
